development:
  adapter: postgresql

test:
  adapter: async

production:
  adapter: postgresql

#development:
#  adapter: async
#
#test:
#  adapter: async
#
#production:
#  adapter: redis
#  url: redis://localhost:6379/1
